Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9 # ImageID valid only in us-east-1 region
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: WebInstance
Outputs:
  InstanceID:
    Description: The Instance ID
    Value: !Ref WebAppInstance
  AZ:
    Description: Availability of the newly created EC2 Instance
    Value: !GetAtt WebAppInstance.AvailabilityZone
  PublicDNS:
    Description: Public DNS of the newly created EC2 Instance
    Value: !GetAtt WebAppInstance.PublicDnsName
  PublicIP:
    Description: Public IP of the newly created EC2 Instance
    Value: !GetAtt WebAppInstance.PublicIp



