Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0d5eff06f840b45e9
    us-west-1:
      AMI: ami-655a0a20
    eu-west-1:
      AMI: ami-7fd4e10b
    ap-southeast-1:
      AMI: ami-72621c20
    ap-northeast-1:
      AMI: ami-8e08a38f
Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap 
        - RegionMap
        - !Ref 'AWS::Region'
        - AMI # ImageID valid only in us-east-1 region
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: WebInstance
Outputs:
  InstanceID:
    Description: The Instance ID
    Value: !Ref WebAppInstance
  AZ:
    Description: Availability of the newly created EC2 Instance
    Value: !GetAtt WebAppInstance.AvailabilityZone
  PublicDNS:
    Description: Public DNS of the newly created EC2 Instance
    Value: !GetAtt WebAppInstance.PublicDnsName
  PublicIP:
    Description: Public IP of the newly created EC2 Instance
    Value: !GetAtt WebAppInstance.PublicIp



